[package]
name = "life-expectancy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copy_to_output = "2.1.0"
csv = "1.2.2"
dict = "0.1.5"
serde = { version = "1.0.164", features = ["serde_derive"] }
